USE [master]
GO

/****** Object:  Database [AbbeSays]    Script Date: 11/27/2011 21:13:08 ******/
IF  EXISTS (SELECT name FROM sys.databases WHERE name = N'AbbeSays')
DROP DATABASE [AbbeSays]
GO

USE [master]
GO

/****** Object:  Database [AbbeSays]    Script Date: 11/27/2011 21:13:08 ******/
CREATE DATABASE [AbbeSays] ON  PRIMARY 
( NAME = N'AbbeSays', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\AbbeSays.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'AbbeSays_log', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\AbbeSays_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [AbbeSays] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [AbbeSays].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [AbbeSays] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [AbbeSays] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [AbbeSays] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [AbbeSays] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [AbbeSays] SET ARITHABORT OFF 
GO

ALTER DATABASE [AbbeSays] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [AbbeSays] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [AbbeSays] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [AbbeSays] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [AbbeSays] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [AbbeSays] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [AbbeSays] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [AbbeSays] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [AbbeSays] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [AbbeSays] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [AbbeSays] SET  DISABLE_BROKER 
GO

ALTER DATABASE [AbbeSays] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [AbbeSays] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [AbbeSays] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [AbbeSays] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [AbbeSays] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [AbbeSays] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [AbbeSays] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [AbbeSays] SET  READ_WRITE 
GO

ALTER DATABASE [AbbeSays] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [AbbeSays] SET  MULTI_USER 
GO

ALTER DATABASE [AbbeSays] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [AbbeSays] SET DB_CHAINING OFF 
GO

